import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

live_config_reload = true

[shell]
program = "tmux"

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Fullscreen"
#decorations_theme_variant = "None"

[colors.primary]
background = "#000000"

[font]
size = 11
